### ISSUE TITLE
Quaternion order

### ISSUE THREAD

**Issue by jmount1992** [petercorke/spatialmath-python#42]
What would be the thoughts around adding an ordering flag/argument to the function `spatialmath.base.q2r`? The `spatialmath.base.r2q` already as this flag/argument. While you have defined a quaternion to have the order (w,x,y,z) [(documentation link)](https://petercorke.github.io/spatialmath-python/3d_quaternion.html?highlight=quaternion#spatialmath.quaternion.Quaternion). There other packages, like ROS, that work in an x,y,z,w order. 

Even without that feature, I think the `q2r` documentation should be explicit about the quaternion order, as it is something that is easy to forget (that different packages use different quaternion orders).

**Comment by petercorke** [comment]
It's a good point, and worth adding to be symmetric.  Agree also that the doco needs some work.  Happy to have PRs :)

I'll put aside some time to integrate a bunch of small PRs and suggestions, and some of my uncommitted tweaks, and push a new release.

**Comment by jmount1992** [comment]
Hopefully, I get some time in the near future, to create a PR for this.

**Comment by petercorke** [comment]
Done on master, to pypi soon
