### ISSUE TITLE
SE3.Rand() uses yrange[0] instead of zrange[0]

### ISSUE THREAD

**Issue by boazsaips** [petercorke/spatialmath-python#56]
Line 1206 in pose3d.py:

`Z = np.random.uniform(low=yrange[0], high=zrange[1], size=N)  # random values in the range`

"low" should be assigned with zrange[0] and not yrange[0].

**Comment by petercorke** [comment]
fixed in 0e79fa3c46ba08e2fdff64ef1bdd0ad2acfa26dd and now in the PyPI version
