### ISSUE TITLE
"nan" returned for the angle when callin SE3.angvec()

### ISSUE THREAD

**Issue by scottnortman** [petercorke/spatialmath-python#57]
When calling angvec() on the SE3 object with the below values:

dTx:   

  1                   3.881e-14    0                  -1.985e-13  
  -3.881e-14   1                   1.438e-11   1.192e-13
   0                 -1.438e-11    1                  0       
   0                  0                   0                  1       

I am getting a returned value of 

 ang:nan

**Comment by petercorke** [comment]
this has been a bit of a problem with matrices that are close, but not equal, to an identity matrix.  This is fixed now on `master` branch and will be included in the PyPi version 1.1.x
