### ISSUE TITLE
Publish new version and update GitHub

### ISSUE THREAD

**Issue by Tobias-Fischer** [petercorke/spatialmath-python#59]
Hi @petercorke,
We are trying to get the RTB to work with emscripten-forge (which compiles into WebAssembly). @wolfv noticed that the geom2d.py file on pypi contains a weird import:
```
from ssl import ALERT_DESCRIPTION_HANDSHAKE_FAILURE
```
Which causes trouble on emscripten-forge. I then noticed that the GitHub repo is out-of-sync (still on version 1.0.0, whereas pypi is at 1.0.1). Is there any chance to remove this odd import, publish a new version 1.0.2, and update the repo?

Many thanks,
Tobi
/cc @jhavl @wolfv

**Comment by petercorke** [comment]
Hi Tobi,

I’ll fix this over the weekend.  I have something weird in my VCS setup, occasionally adds random imports at top of files.

Peter

**Comment by petercorke** [comment]
@Tobias-Fischer fixed now and on PyPI.  Internet crapped out on me, so only the wheel file got through. Let me know if you need the zip file.

**Comment by wolfv** [comment]
I think the source dist would be preferred. We can also take it from GitHub if you make the tag.

**Comment by petercorke** [comment]
@wolfv the source distro is there now as release 1.0.3.

**Comment by wolfv** [comment]
awesome!

**Comment by Tobias-Fischer** [comment]
Thanks @petercorke!

**Comment by wolfv** [comment]
It works -- here is a version that runs _in the browser_ and also plots some nice diagrams from the docs :) Only downside is that it's a 70Mb download.

https://wolfv.github.io/try-spatialgeometry/lab?path=spatialmath_demo.ipynb

Btw. I saw that you looked at scikit-geometry for Polygon functions. Unfortunately I haven't found much time to maintain it recently, but would be happy to push a little bit on it to make it easy to install via pip as well.

**Comment by petercorke** [comment]
Thanks Wolf.  I am super excited about WASM.  Is the 70Mb just for SMTB, or does that include dependencies like MPL and NumPy? 

Sorry, I’d forgotten about scikit.  I think I ended up using Matplotlib functionality for this, to reduce the number of dependencies that I have.

Peter

**Comment by wolfv** [comment]
Yes, the 70 mb contain everything including matplotlib and numpy.

No worries, happy that you found a solution with fewer dependencies.

**Comment by petercorke** [comment]
Hi @wolfv , chatting with @jhavl it seems like 30Mb of that is scipy and I can remove those dependencies with a few simple tweaks.  Just need to test and push.
