### ISSUE TITLE
The tol is too tricky

### ISSUE THREAD

**Issue by tranminhduc4796** [petercorke/spatialmath-python#6]
I'm using the module on KITTI dataset and I found a problem that your module is using tol=100 which is really tricky to check valid SO3 or SE3 matrix (orthogonal or not). Could you give a function to set up the tol value or increase the tol to 1e9?

**Comment by petercorke** [comment]
Many of the low level functions allow you to set tol, in units of eps.  1e9 is a pretty loose definition of SO(3) or SE(3).  Specifically which functions are you concerned about?

**Comment by tranminhduc4796** [comment]
They are class SO(3) and SE(3). When I apply the class to the matrix even with the check=False. When I use some methods (maybe rpy or exp, if I am not wrong), they use the function isvalid with default value of to which lead to exception.  Currently, I am using low-level functions instead of the class but I guess it would be better to enable to set the tol value when init.

**Comment by petercorke** [comment]
Might be easiest to clone and change what you need to. Or you could rework the code so there is a package constant that is changed once globally.

**Comment by petercorke** [comment]
Another option is to apply base.trnorm() to your matrix before you pass them to SE3 constructor.  This will make the rotation part proper, see the doco about what it does and if it’s suitable for your purpose.

**Comment by tranminhduc4796** [comment]
Thank you so much. I will try this trick later. I think it would work well for my case.
