### ISSUE TITLE
Line3 multiplication with SE3 not working properly

### ISSUE THREAD

**Issue by lgjonathan** [petercorke/spatialmath-python#64]
Hi,
Currently the __rmul__ works like follows

`SE3.Rt(R=matrix.R, t=(0,0,0)) * SE3.Trans(matrix.t) * line
`

However, it should work like below.
` SE3.Trans(matrix.t) * SE3.Rt(R=matrix.R, t=(0,0,0)) * line
`
It should translate the line first and then rotate it.
Or am I missing something?

**Comment by petercorke** [comment]
I confess I haven't seen/found any definitive reference about this. I simply multiplied the Plucker coordinates by the adjoint matrix, which is the way that twists (a related R^6 vector) are transformed.  This definitely does the right thing for pure translation.  For the case of rotation there is the question about what point on the line the rotation is about, my guess is it will rotate about the principal point.
