### ISSUE TITLE
AttributeError: module 'spatialmath' has no attribute 'base'

### ISSUE THREAD

**Issue by mohseni-fatemeh** [petercorke/spatialmath-python#66]
the issue comes from this line 

**`import spatialmath.base as smb`**

in the file : 

**spatialmath-python/spatialmath/base/transforms2d.py", line 20 .**

this line gives the following error : 

 **import spatialmath.base as smb
AttributeError: module 'spatialmath' has no attribute 'base'**

the solution is to change import model from above to below : 

:+1: **`from spatialmath import base as smb`**

**Comment by petercorke** [comment]
this is odd. that code runs on Python 3.7 to 3.11 on Mac/Win/Linux.  what are you running it on?

**Comment by mohseni-fatemeh** [comment]
pyhton 3.8 . ubuntu 22

**Comment by petercorke** [comment]
I have no idea what is going on.  The existing version works find for me, and as I mentioned it passes unit tests on lots of python/os combos including the one you are running.  If more folk flag this I'll make changes, but for now I'm closing this.
