### ISSUE TITLE
Length parameter is wrongly applied

### ISSUE THREAD

**Issue by hadibeikm** [petercorke/spatialmath-python#7]
In the code related to applying length to each axis in this snippet: (transforms3D.py)
x = T @ np.array([1, 0, 0, 1]) * length
y = T @ np.array([0, 1, 0, 1]) * length
z = T @ np.array([0, 0, 1, 1]) * length
The length should not be multiplied by the last element
x = T @ np.array([1* length, 0, 0, 1])
y = T @ np.array([0, 1 * length, 0, 1])
z = T @ np.array([0, 0, 1 * length, 1])

**Comment by petercorke** [comment]
This was recently fixed, git pull
